[package]
name = "parq"
version = "0.1.0"
description = "A blazingly-fast tool for exploring and analyzing Apache Parquet file: inspect schema, view statistics, browse data, and dissect structures"
authors = ["Sergey Olontsev <sergey@olontsev.io>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
parquet = "57.1.0"
thiserror = "2.0.17"
