[package]
name = "parq"
version = "0.1.0"
description = "A blazingly-fast tool for exploring and analyzing Apache Parquet file: inspect schema, view statistics, browse data, and dissect structures"
authors = ["Sergey Olontsev <sergey@olontsev.io>"]
license = "Apache-2.0"
edition = "2024"
repository = "https://github.com/solontsev/parq"
homepage = "https://github.com/solontsev/parq"
readme = "README.md"
keywords = ["parquet", "cli", "tui", "data-analysis"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "parq"
path = "src/bin/parq.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
parquet = "57.1.0"
thiserror = "2.0.17"
ratatui = "0.30.0"
crossterm = "0.29.0"
anyhow = "1.0.100"
chrono = "0.4.43"
byte-unit = "5.2.0"
num-format = "0.4.4"
